### PR TITLE
Add UPF-P4 SW component

### PR DESCRIPTION
**Pull request by rafagarciaUMA**
Add UPF-P4 SW component from my 'upf_p4_sw' branch to 'develop' branch.

### CODE REVIEW

**Comment by alvarocurt** [comment]
Thank you so much Rafa.
Before merging, could you please remove the (autogenerated) files inside variables?
Those are just placeholder files from the dummy component to show where variables are loaded during the deployment, but have no real purpose in a functional component's code
Besides that, I think everything looks nice.

**Comment by alvarocurt** [comment]
Additional comments:
- I've seen some unencripted certificates published as blank files. Is that intentional? Isn't that a huge security flaw?
- I would suggest adding the IPs and VM ID to the TNLCM callback. Process is really simple, you already load those variables during the main ansible playbook execution.
- You have 2 extra task checking if the terraform outputs are correctly created. I never had to do that. Did you encounter any problems with that during development? I'm actually interested, in case those checks should be added to more components

**Review by alvarocurt — CHANGES_REQUESTED** [review]
Review on comments

**Review by alvarocurt — APPROVED** [review]

**Comment by rafagarciaUMA** [comment]
Thank you so much Alvaro for your thorough review! I've addressed all your comments:

- I've removed all the autogenerated files from the variables directory
- I've deleted the freeDiameter certificates. They were accidentally left over from open5gs 4G setup and are not needed for this component.
- I've added the IPs and VM ID to the TNLCM callback as suggested.
- Regarding the two extra tasks that check terraform outputs: I personally haven't experienced any issues with outputs in this component, but I had some problems with my other P4 telemetry component where I have different outputs. These tasks aren't strictly necessary really. I added them after reading about it as a "best practice" (thanks ChatGPT 😅)

**Pull request merged**
